app/routes/auth.py
from app.extensions import db, login_manager
from app.models import User, Overlay
from flask import Blueprint, request, jsonify, redirect, url_for, session, current_app, Response
from flask_login import login_user, logout_user
from requests_oauthlib import OAuth2Session
import uuid


auth_bp = Blueprint('auth', __name__, url_prefix='/auth')

DISCORD_API_BASE_URL = "https://discord.com/api"
DISCORD_AUTHORIZATION_BASE_URL = f"{DISCORD_API_BASE_URL}/oauth2/authorize"
DISCORD_TOKEN_URL = f"{DISCORD_API_BASE_URL}/oauth2/token"

@login_manager.user_loader
def load_user(user_id: str) -> User:
    return db.session.query(User).get(int(user_id))

def token_updater(token: dict) -> None:
    session["oauth2_token"] = token

def make_session(token=None, state=None, scope=None) -> OAuth2Session:
    return OAuth2Session(
        current_app.config.get("DISCORD_CLIENT_ID"),
        token=token,
        state=state,
        scope=scope,
        redirect_uri=current_app.config.get("DISCORD_REDIRECT_URI"),
        auto_refresh_kwargs={
            'client_id': current_app.config.get("DISCORD_CLIENT_ID"),
            'client_secret': current_app.config.get("DISCORD_CLIENT_SECRET"),
        },
        auto_refresh_url=current_app.config.get(DISCORD_TOKEN_URL),
        token_updater=token_updater
    )

@auth_bp.route('/login', methods=['GET'])
def login() -> Response:
    discord = make_session(scope=['identify'])
    authorization_url, state = discord.authorization_url(DISCORD_AUTHORIZATION_BASE_URL)
    session['oauth_state'] = state
    return redirect(authorization_url)

@auth_bp.route('/callback', methods=['GET'])
def callback() -> Response:
    discord = make_session(state=session['oauth_state'])
    token = discord.fetch_token(
        DISCORD_TOKEN_URL,
        client_secret=current_app.config.get("DISCORD_CLIENT_SECRET"),
        authorization_response=request.url
    )

    if 'access_token' not in token:
        return jsonify({"error": "Failed to obtain access token"}), 400

    token_updater(token)

    discord = make_session(token=token)
    user_info_url = f"{DISCORD_API_BASE_URL}/users/@me"
    user_info_response = discord.get(user_info_url)
    user_info = user_info_response.json()

    user = load_user(user_info['id'])
    if(user is None):
        user = User(id=user_info['id'], username=user_info['username'])
        overlay = Overlay(id=uuid.uuid4().hex, user_id=user.id)
        user.overlay = overlay
        db.session.add(user)
        db.session.add(overlay)
        db.session.commit()
        db.session.refresh(user)
    login_user(user)

    return redirect(url_for('overlay.manage'))

@auth_bp.route('/logout', methods=['GET'])
def logout() -> Response:
    session.clear()
    logout_user()
    return redirect(url_for('index'))

app/routes/overlay.py
from app.extensions import db, socketio
from app.models import Overlay
from flask import Blueprint, render_template, Response, request
from flask_login import login_required, current_user

overlay_bp = Blueprint('overlay', __name__, url_prefix='/overlay')

@overlay_bp.route('/manage', methods=['GET'])
@login_required
def manage() -> Response:
    return render_template('management.html.j2')

@overlay_bp.route('/manage', methods=['PUT'])
@login_required
def update():
    update_data = request.json
    current_user.overlay.update(update_data)
    socketio.emit('update', update_data, room=current_user.overlay.id)
    return Response(status=200)

@overlay_bp.route('/<overlay_id>', methods=['GET'])
def overlay(overlay_id: str) -> Response:
    overlay = db.get_or_404(Overlay, overlay_id)
    return render_template('overlay.html.j2', overlay=overlay)

app/templates/base.html.j2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Commander Overlay - {% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="{{ url_for('static', filename='css/overlay.css') }}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block header %}{% endblock %}
</head>
<body>
    {% block content %}{% endblock %}
    <footer class="position-fixed bottom-0 d-flex flex-wrap justify-content-between align-items-center px-3 my-4 w-100">
        <div class="col-4 mb-0 text-muted text-end">Commander Overlay</div>
        <span class="col-4 mb-0 text-center">
            Like the site? I appreciate any <a class="link-secondary" href="https://paypal.me/norwegianwhaler?country.x=US&locale.x=en_US">tips!</a>
        </span>
        <div class="d-flex col mb-0 justify-content-start">
            <a class="fs-2 link-secondary" href="https://github.com/linkian209/CommanderOverlay"><i class="bi bi-github"></i></a>
        </div>
    </footer>
</body>
</html>

app/templates/error.html.j2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>404 Not Found</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            font-family: Arial, sans-serif;
            background-color: #f8f8f8;
        }
        .container {
            text-align: center;
        }
        .container img {
            max-width: 100%;
            height: auto;
        }
        .container h1 {
            font-size: 2em;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <img src="{{ url_for('static', filename='img/sorry.svg') }}" alt="Sorry">
        <h1>404 - Page Not Found</h1>
        <p>Sorry, the page you are looking for does not exist.</p>
    </div>
</body>
</html>

app/templates/index.html.j2
{% extends "base.html.j2" %}

{% block title %}Index{% endblock %}

{% block header %}<link href="{{ url_for('static', filename='css/index.css') }}" rel="stylesheet">{% endblock %}

{% block content %}
    <div id="welcome" class="container-fluid">
        <h1>Welcome to Commander Overlay!</h1>
        <hr>
        <a href="{{ url_for('auth.login') }}" class="btn btn-primary">
            <i class="bi bi-discord"></i> Login with Discord
        </a>
    </div>
    <div id="p1" class="banner top-left top-left-trap" style="padding-right: 40.1px; background: linear-gradient(rgb(14, 104, 171), rgb(0, 115, 62));">
        <div id="p1-title" class="title top-left-trap ps-3" style="width: 441.1px">Kinnan, Bonder Prodigy</div>
    </div>
    <div id="p2" class="banner top-right top-right-trap" style="padding-left: 85.4px; background: rgb(211, 32, 42)">
        <div id="p2-title" class="title top-right-trap pe-3" style="width: 939.4px">Slicer, Hired Muscle // Slicer, High-Speed Antagonist</div>
    </div>
    <div id="p4" class="banner bottom-left bottom-left-trap" style="padding-right: 50.8px; background: linear-gradient(rgb(14, 104, 171), rgb(21, 11, 0), rgb(211, 32, 42));">
        <div id="p4-title" class="title bottom-left-trap ps-3" style="width: 558.8px;">
            Rograkh, Son of Rohgahh
            <br>
            Silas Renn, Seeker Adept
        </div>
    </div>
    <div id="p3" class="banner bottom-right bottom-right-trap" style="padding-left: 47.9px; background: linear-gradient(rgb(14, 104, 171), rgb(21, 11, 0));">
        <div id="p3-title" class="title bottom-right-trap pe-3" style="width: 526.9px;">Yuriko, the Tiger's Shadow</div>
    </div>
{% endblock %}

app/templates/management.html.j2
{% extends "base.html.j2" %}

{% block title %}Management{% endblock %}

{% block header%}
    <link href="{{ url_for('static', filename='css/management.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center p-3 min-vh-100 flex-column" style="background-color: #DADADA;">
        <div class="container">
            <div class="row">
                <div class="col-md-6 top-left-cell">
                    <div class="mb-3">
                        <h2>Player 1</h2>
                        <label for="commander1p1" class="form-label">Commander 1</label>
                        <div class="input-group">
                            <input type="text" class="form-control autocomplete" id="commander1-p1" name="commander1p1" placeholder="Type Commander 1">
                            <button type="button" class="btn bg-transparent" style="margin-left: -40px; z-index: 100;" data-commanderplayer="commander1-p1">
                                <i class="bi bi-x"></i>
                            </button>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="commander2p1" class="form-label">Commander 2</label>
                        <div class="input-group">
                            <input type="text" class="form-control autocomplete" id="commander2-p1" name="commander2p1" placeholder="Type Commander 2">
                            <button type="button" class="btn bg-transparent" style="margin-left: -40px; z-index: 100;" data-commanderplayer="commander2-p1">
                                <i class="bi bi-x"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 top-right-cell">
                    <div class="mb-3">
                        <h2>Player 2</h2>
                        <label for="commander1p2" class="form-label">Commander 1</label>
                        <div class="input-group">
                            <input type="text" class="form-control autocomplete" id="commander1-p2" name="commander1p2" placeholder="Type Commander 1">
                            <button type="button" class="btn bg-transparent" style="margin-left: -40px; z-index: 100;" data-commanderplayer="commander1-p2">
                                <i class="bi bi-x"></i>
                            </button>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="commander2p2" class="form-label">Commander 2</label>
                        <div class="input-group">
                            <input type="text" class="form-control autocomplete" id="commander2-p2" name="commander2p2" placeholder="Type Commander 2">
                            <button type="button" class="btn bg-transparent" style="margin-left: -40px; z-index: 100;" data-commanderplayer="commander2-p2">
                                <i class="bi bi-x"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 bottom-right-cell order-md-last">
                    <div class="mb-3">
                        <h2>Player 3</h2>
                        <label for="commander1p3" class="form-label">Commander 1</label>
                        <div class="input-group">
                            <input type="text" class="form-control autocomplete" id="commander1-p3" name="commander1p3" placeholder="Type Commander 1">
                            <button type="button" class="btn bg-transparent" style="margin-left: -40px; z-index: 100;" data-commanderplayer="commander1-p3">
                                <i class="bi bi-x"></i>
                            </button>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="commander2p3" class="form-label">Commander 2</label>
                        <div class="input-group">
                            <input type="text" class="form-control autocomplete" id="commander2-p3" name="commander2p3" placeholder="Type Commander 2">
                            <button type="button" class="btn bg-transparent" style="margin-left: -40px; z-index: 100;" data-commanderplayer="commander2-p3">
                                <i class="bi bi-x"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 bottom-left-cell">
                    <div class="mb-3">
                        <h2>Player 4</h2>
                        <label for="commander1p4" class="form-label">Commander 1</label>
                        <div class="input-group">
                            <input type="text" class="form-control autocomplete" id="commander1-p4" name="commander1p4" placeholder="Type Commander 1">
                            <button type="button" class="btn bg-transparent" style="margin-left: -40px; z-index: 100;" data-commanderplayer="commander1-p4">
                                <i class="bi bi-x"></i>
                            </button>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="commander2p4" class="form-label">Commander 2</label>
                        <div class="input-group">
                            <input type="text" class="form-control autocomplete" id="commander2-p4" name="commander2p4" placeholder="Type Commander 2">
                            <button type="button" class="btn bg-transparent" style="margin-left: -40px; z-index: 100;" data-commanderplayer="commander2-p4">
                                <i class="bi bi-x"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="overlay_url" class="form-label">Overlay URL</label>
                <div class="input-group">
                    <input type="text" class="form-control" id="overlay_url" value="{{ url_for('overlay.overlay', overlay_id=current_user.overlay.id, _external=True) }}" disabled>
                    <button class="btn btn-primary" type="button" onclick="copyToClipboard()">Copy</button>
                </div>
                <a href="{{ url_for('auth.logout') }}" class="btn btn-danger mt-3">Logout</a>
            </div>
        </div>

        <script>
            function copyToClipboard() {
                const toast = new bootstrap.Toast(document.getElementById("copied_toast"));

                var url = document.getElementById("overlay_url");
                url.select();
                url.setSelectionRange(0, 99999);
                navigator.clipboard.writeText(url.value);

                toast.show();
            }
        </script>
    </div> 
    <div class="toast-container position-fixed bottom-0 end-0 p-3">
        <div id="copied_toast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="d-flex">
                <div class="toast-body">URL Copied!</div>
                <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
        </div>
    </div>
    <div id="p1" class="banner top-left top-left-trap" style="visibility: hidden">
        <div id="p1-title" class="title top-left-trap ps-3"></div>
    </div>
    <div id="p2" class="banner top-right top-right-trap" style="visibility: hidden">
        <div id="p2-title" class="title top-right-trap pe-3"></div>
    </div>
    <div id="p4" class="banner bottom-left bottom-left-trap" style="visibility: hidden">
        <div id="p4-title" class="title bottom-left-trap ps-3"></div>
    </div>
    <div id="p3" class="banner bottom-right bottom-right-trap" style="visibility: hidden">
        <div id="p3-title" class="title bottom-right-trap pe-3"></div>
    </div>
    <script type="module">
        import Autocomplete from "https://cdn.jsdelivr.net/gh/lekoala/bootstrap5-autocomplete@master/autocomplete.js";
        import { updateDisplay, loadCommanders } from "{{ url_for('static', filename='js/util.js') }}";
        import { io } from "https://cdn.socket.io/4.7.5/socket.io.esm.min.js";

        var commanders = loadCommanders({{ current_user.overlay.to_dict() | tojson }});
        
        const socket = io();

        Autocomplete.init("input.autocomplete", {
            source: function (term, response) {
                fetch(`https://api.scryfall.com/cards/autocomplete?q=${term}`)
                    .then(response => response.json())
                    .then(data => {
                        response(data.data);
                    });
            },
            onSelectItem: function (item, autocomplete) {
                console.log("Item selected", item, autocomplete);
                let [commander_number, player_number] = autocomplete._searchInput.id.split('-');
                fetch(`https://api.scryfall.com/cards/named?exact=${item.label}`)
                    .then(response => response.json())
                    .then(cardData => {
                        commanders[player_number][commander_number]["name"] = cardData.name;
                        commanders[player_number][commander_number]["colors"] = cardData.color_identity;

                        updateDb()
                        .catch(error => console.error('Error updating database:', error));

                    })
                    .catch(error => console.error('Error fetching card data:', error));
            },
            fullWidth: true,
            preventBrowserAutocomplete: true,
            highlightTyped: false
        });

        function clear(id) {
            document.getElementById(id).value = "";
            let [commander_number, player_number] = id.split('-');
            commanders[player_number][commander_number].name = "";
            commanders[player_number][commander_number].colors = [];
            updateDb().catch(error => console.error('Error updating database:', error));
        }

        function updateDb() {
            return fetch("{{ url_for('overlay.manage') }}", {
                method: 'PUT',
                headers: {
                    'Content-Type': 'application/json; charset=UTF-8'
                },
                body: JSON.stringify({
                    player1_commander1: commanders["p1"]["commander1"]["name"],
                    player1_commander1_ci: commanders["p1"]["commander1"]["colors"].join(","),
                    player1_commander2: commanders["p1"]["commander2"]["name"],
                    player1_commander2_ci: commanders["p1"]["commander2"]["colors"].join(","),
                    player2_commander1: commanders["p2"]["commander1"]["name"],
                    player2_commander1_ci: commanders["p2"]["commander1"]["colors"].join(","),
                    player2_commander2: commanders["p2"]["commander2"]["name"],
                    player2_commander2_ci: commanders["p2"]["commander2"]["colors"].join(","),
                    player3_commander1: commanders["p3"]["commander1"]["name"],
                    player3_commander1_ci: commanders["p3"]["commander1"]["colors"].join(","),
                    player3_commander2: commanders["p3"]["commander2"]["name"],
                    player3_commander2_ci: commanders["p3"]["commander2"]["colors"].join(","),
                    player4_commander1: commanders["p4"]["commander1"]["name"],
                    player4_commander1_ci: commanders["p4"]["commander1"]["colors"].join(","),
                    player4_commander2: commanders["p4"]["commander2"]["name"],
                    player4_commander2_ci: commanders["p4"]["commander2"]["colors"].join(",")
                })
            });
        }


        document.querySelectorAll("button[data-commanderplayer]").forEach(button => {
            button.addEventListener("click", function() {
                clear(this.getAttribute("data-commanderplayer"));
            });
        });

        Object.keys(commanders).forEach(player_number => {
            Object.keys(commanders[player_number]).forEach(commander_number => {
                document.getElementById(commander_number+"-"+player_number).value = commanders[player_number][commander_number].name;
                updateDisplay(player_number, commanders[player_number]["commander1"], commanders[player_number]["commander2"]);
            });
        });

        setTimeout(() => {
            Object.keys(commanders).forEach(player_number => {
                Object.keys(commanders[player_number]).forEach(commander_number => {
                    updateDisplay(player_number, commanders[player_number]["commander1"], commanders[player_number]["commander2"]);
                    document.getElementById(player_number).style.visibility = "";
                });
            });
        }, 250);

        socket.on("connect", () => {
            console.log("Connected to server");
            socket.emit("join", "{{ current_user.overlay.id }}");
        });

        socket.on("update", data => {
            console.log("Received update: ", data);
            commanders = loadCommanders(data);
            Object.keys(commanders).forEach(player_number => {
                Object.keys(commanders[player_number]).forEach(commander_number => {
                    document.getElementById(commander_number+"-"+player_number).value = commanders[player_number][commander_number].name;
                    updateDisplay(player_number, commanders[player_number]["commander1"], commanders[player_number]["commander2"]);
                });
            });
        });

    </script>
{% endblock %}

app/templates/overlay.html.j2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Commander Overlay - {{ overlay.id }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{{ url_for('static', filename='css/overlay.css') }}" rel="stylesheet">
</head>
<body>
    <div id="p1" class="banner top-left top-left-trap" style="visibility: hidden">
        <div id="p1-title" class="title top-left-trap ps-3"></div>
    </div>
    <div id="p2" class="banner top-right top-right-trap" style="visibility: hidden">
        <div id="p2-title" class="title top-right-trap pe-3"></div>
    </div>
    <div id="p4" class="banner bottom-left bottom-left-trap" style="visibility: hidden">
        <div id="p4-title" class="title bottom-left-trap ps-3"></div>
    </div>
    <div id="p3" class="banner bottom-right bottom-right-trap" style="visibility: hidden">
        <div id="p3-title" class="title bottom-right-trap pe-3"></div>
    </div>
    <script type="module">
        import { updateDisplay, loadCommanders } from "{{ url_for('static', filename='js/util.js') }}";
        import { io } from "https://cdn.socket.io/4.7.5/socket.io.esm.min.js";

        var commanders = loadCommanders({{ overlay.to_dict() | tojson }});

        const socket = io();

        Object.keys(commanders).forEach(player_number => {
            Object.keys(commanders[player_number]).forEach(commander_number => {
                updateDisplay(player_number, commanders[player_number]["commander1"], commanders[player_number]["commander2"]);
            });
        });

        setTimeout(() => {
            Object.keys(commanders).forEach(player_number => {
                Object.keys(commanders[player_number]).forEach(commander_number => {
                    updateDisplay(player_number, commanders[player_number]["commander1"], commanders[player_number]["commander2"]);
                    document.getElementById(player_number).style.visibility = "";
                });
            });
        }, 250);

        socket.on("connect", () => {
            console.log("Connected to server");
            socket.emit("join", "{{ overlay.id }}");
        });

        socket.on("update", (data) => {
            commanders = loadCommanders(data);
            Object.keys(commanders).forEach(player_number => {
                Object.keys(commanders[player_number]).forEach(commander_number => {
                    updateDisplay(player_number, commanders[player_number]["commander1"], commanders[player_number]["commander2"]);
                });
            });
        });
    </script>
</body>
</html>